package com.cartones.de.bingo.en.casa.gratis.loteria.ui.domains.models

data class NumberCard (
    val number1: Int,
    val number2: Int,
    val number3: Int,
    val number4: Int,
    val number5: Int,
    val number6: Int,
    val number7: Int,
    val number8: Int,
    val number9: Int,
    val number10: Int,
    val number11: Int,
    val number12: Int,
    val number13: Int,
    val number14: Int,
    val number15: Int,
    val number16: Int,
    val number17: Int,
    val number18: Int,
    val number19: Int,
    val number20: Int,
    val number21: Int,
    val number22: Int,
    val number23: Int,
    val number24: Int,
  val number25: Int,
  val number26: Int,
  val number27: Int
    )
